services:
  shared-mysql-db:
    image: mysql:8
    container_name: shared-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 15243
      MYSQL_DATABASE: hotel_system
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
